Make the toggle collision work
aldelaro5/BugFables-Speedrun-Practice pull request #8
Opened 2021-02-20 03:41 UTC by Lyght-1

-fix the collision bug
-fix getting stuck on a wall for a sec even with collision off.

2021-02-20 05:34 UTC, aldelaro5 requested changes
New files should be indented by 2 spaces and existing file changes had indentation change which I would like to see reverted.

Other than that LGTM, but like I mentioned with the collision viewer PR, I would need to test this, though this should be approved relatively quickly.

2021-02-20 05:34 UTC, aldelaro5 commented on Extensions/PlayerControl_Ext.cs
> +					__instance.entity.hitwall = false;
indentation

2021-02-20 05:34 UTC, aldelaro5 commented on Patches/EntityControl.cs
> +        }
Indentation changed, pls keep it to 2 spaces.

2021-02-20 05:34 UTC, aldelaro5 commented on Patches/GroundDetector.cs
> +}
Indentation.

2021-02-20 05:34 UTC, aldelaro5 commented on Patches/RayDetector.cs
> +}
Indentation

2021-02-25 02:03 UTC, aldelaro5 commented
Hey, just a reminder if it is possible to address my code reviews (and answer question cause there was one line that was confusing me) because I expect to actually come back to this in a few days so if the code reviews are addressed by the time I get to testing, it will make it quick.

Due to how urgent 2 of your prs are, I might be forced to merge as is when I confirm my tests, but keep in mind that I will have to fix the issues myself which isn't what you would do normally (you are supposed to address the issues yourself before I merge). What this means is that although it might pass for these prs because they are urgent, I am normally am not going to merge until the code reviews are addressed which is going to block further prs. Just to let you know.

2021-02-27 00:10 UTC, aldelaro5 commented
Last call: if this isn't addressed by Saturday after my tests, I am forced to preemptively merge and take over the PRs. Since 2 of your PRs will generate I conflict, I will have to coauthor one of them (normally I would ask permissions, but it's urgent enough to do it if I am forced to).

In the event that you can't address these reviews, please know that I won't do this next time. If I post a code review, pls address it before we can move on.

2021-02-27 06:03 UTC, Lyght-1 commented
Should be good now ?

2021-02-27 06:40 UTC, aldelaro5 approved these changes
LGTM, though I kinda want to check why that prefix on the grounDetector was needed because in theory, this event can't fire if the existing monoBehaviour is disabled, but this is urgent to merge so it will have to do for now

2021-02-27 06:40 UTC, merged

2021-02-27 07:01 UTC, aldelaro5 commented
> Should be good now ?

yeah, I just made a release, might check your new pr now though because it seems urgent.

Btw, was the GroundDetector patch needed? Unity shouldn't fire events on disabled objects

2021-02-27 07:06 UTC, Lyght-1 commented
Yes it was. OnTrigger events are still called even if the object is disabled.

2021-02-27 07:08 UTC, aldelaro5 commented
huh 
``` Note: Trigger events are only sent if one of the colliders also has a rigidbody attached. Trigger events are sent to disabled MonoBehaviours to allow enabling Behaviours in response to collisions.```
I didn't know that!